var currentTextArray = [];
var maxLineSize = 50;
var numLinesShown = 20;
var currentTextIndex = 0;
var interpolationTime = 0;
var timeBetweenSentence = 0;


function getRandomTextLocation()
{
    var point = {};
    point.x = (Math.random() * CANVAS_WIDTH * 0.5);
    point.y = (Math.random() * CANVAS_HEIGHT * 0.5);
    return point;
}

function getTextToDisplay()
{
    return currentTextArray[currentTextIndex];
}

function incrementTextIndex()
{
    currentTextIndex++;
    interpolationTime = (new Date()).getTime();
}

function fetchNewText()
{
    currentTextIndex = 0;
    currentTextArray = [];
    requestNextLine();
}

function ingestText(text, timeForEachLine, timeBeforeFetchingNextStory)
{
    timeBetweenSentence = timeForEachLine;
    var sentenceList = text.split("~~ ");
    var y = 0;
    for (; y < sentenceList.length; y++)
    {
        var x = 0;
        var textLine = "";
        var splitList = sentenceList[y].split(" ");
        
        var sentenceArray = [];
        for (; x < splitList.length; x++)
        {
            if (textLine.length + splitList[x].length + 1 >= maxLineSize)
            {
                //needed if the first element is larger that the max line size. Just add it anyways.
                if (x != 0)
                {
                    sentenceArray.push(textLine);
                }
                
                textLine = "";
            }
            
            textLine += splitList[x] + " ";
        }
        
        if (textLine.length > 0)
        {
            sentenceArray.push(textLine);
        }
        
        var obj = {};
        obj.text = sentenceArray;
        obj.point = getRandomTextLocation()
        currentTextArray.push(obj);
    }
    for (y = 0; y < currentTextArray.length; y++)
    {
        setTimeout(incrementTextIndex, (y + 1) * timeForEachLine * 1000);
    }
    
    setTimeout(fetchNewText, ((currentTextArray.length + 1) * timeForEachLine + timeBeforeFetchingNextStory) * 1000);
    interpolationTime = (new Date()).getTime();
}



function getNextLine() {
    
    var randIndex = Math.floor(Math.random() * storyLineData.length);
    
    
    return { line: storyLineData[randIndex], timeToNextStory:60, timeForEachLine:5 };
}









let storyLineData = [
                     "You know, back when I was young, even younger than you are now, I used to love the water.~~ That smell on the shoreline.~~ The way the water laps up at you, greeting you.~~ It’s something you can’t get anywhere else.~~ Except the ocean of course, but that’s just different water.~~ Saltier, though I don’t mind the brine all that much.~~ That kinda smell builds character.~~ That’s what they mean when you’re “worth your salt”, that you can hold your own on the sea until your as brine encrusted as the ship you sail on.",
                     "There’s something nice about fishing at night.~~ There’s a calm serenity you don’t get during the day.~~ Ain’t nearly as many sounds, though the bugs are much worse.~~ They don’t bother me much anymore.~~ I figure I’m so wrinkly they think I’m all dried out!~~ Of course the fishing is easier too, not nearly as many folks out to scare ‘em off or snatch ‘em before me.~~ Lucky I found this little secluded spot.~~ Right here it’s just you, me, and the fish.~~ Nobody to disrupt us.",
                     "Did I ever tell you about how I got started fishing?~~ When I was about five years old my own old man came up to me after church and said “Son, you and your Pop are gonna catch the biggest bass this town’s ever seen.” See, he had this bet with the other workers at the plant that he’d have his son catching fish long before he started chasing women.~~ Well, we went out with his pole and I made a little rinky-dink one out of a stick and some thread.~~ We hopped up into his old beat up pickup and drove around twenty miles to the river that ran through a nearby farm.~~ We must’ve been there for hours.~~ ",
                     "Turns out there weren’t any fish in that water!~~ We sat, and waiting, and talked for ages and just as the sun started to set, we packed up and drove to the market.~~ Made it in just before closing and bought the largest fish they had.~~ We took it home, snapped a picture and the next morning my Pop came home a whole fifteen dollars richer.~~ He gave me ten I told me to do whatever I wanted with it.~~ So I bought my own rod and started finding better spots to fish together.~~ I haven’t missed a weekend since.",
                     "You’re a good fishing partner you know.~~ You don’t say much and that doesn’t disturb the fish.~~ Me?~~ Well, I suppose I’m a bit of a blabber mouth, but really I ain’t had anyone to fish with in a long time.~~ My wife was never too big on it and she passed away a while ago.~~ I don’t really know where my kids went.~~ I had two of ‘em: Alexander and Samantha.~~ They went off to college and never really came back, save for the holidays.~~ They moved to opposite ends of the country and have their own family now.~~ I miss ‘em, but I’ll always have the fish… and you!",
                     "As a kid, I used to think of fish as bugs.~~ Like, they just kinda milled about nibbling at whatever they came across.~~ The older I get the more I figure we’re all like that really.~~ Just milling about, nibbling at whatever we come across.",
                     "You know, I’ve got a mighty chill out here.~~ Reminds me of the winter of ‘43.~~ I was a young man and my goodness did the now come fast.~~ Why, the day before I’d woken up and it was clear as always.~~ Next morning I open the window and there was snow up past my chest.~~ Why I saw the dog go out and try to swim through it to pee and he returned half ice!~~ Well, I snatched up my coat because I still had to get to the schoolhouse and grabbed a piece of toast and began my hike.~~ It was a good hour walk on a sunny day but the winds nearly picked me up and threw me to school.~~ I suppose they wanted me to get there as much as I did.~~ My only saving grace were the nickels I had in my pocket.~~ I’d heard of ice climbing’ boots and so I stuffed them into the soles and used ‘em to hold me to the ground as I trudged along.~~ I barely made it on time but my shoes had holes in ‘em that sent my Mom into a tizzy when I got home.~~ I had to give up my allowance for a year to buy new shoes and drove some nails through the old ones to make my own cleats.~~ I think I still have them somewhere around my house.",
                     "Ever caught the rare red floozer?~~ I’ve been laughed out of bars for years but I swear I’ve caught at least five in my life.~~ They’re these slim little things with long red fins down the sides of their pinkish bodies.~~ Well, I know they’re in this water here and I’m not leaving until I catch one and bring it door to door to prove each and every one of them wrong.~~ They’re slippery though, I swear I’ve dropped ‘em all long before I meant to.~~ Though fish like that belong out in the water.~~ I release every one I’ve caught, except the ones I’ve cooked.~~ If you catch them again it’s kinda like meeting an old friend.",
                     "What is it you kids do for fun these days?~~ When I was a kid all I did for fun was fishing and a little game the neighborhood boys called “Slip Ship” we’d go out into the woods and build a tree fort and then cover the whole thing with lard.~~ Last man atop the fort was the winner while everyone else had to either knock the others off or tear the fort down from below.~~ It was probably the most fun I ever had.~~ These days they’d probably never let you near that kinda thing.~~ Your parents watch you too much I think.~~ There’s just no time to be a kid out in the wild anymore… Shame...",
                     "What kind of rod do you use?~~ I use a Plusinno Fishing Rod and Reel, I bought it for my son but he didn’t take to the water the same way I did, so once my old pole got too worn down and broke off in a grouper’s mouth I dug this old thing out and have been using it ever since.~~ It works pretty well, though it ain’t the same as my old reliable.~~ I suppose change takes getting used to, you know?",
                     "If you don’t mind me asking, could you help me open up this can of worms?~~ Damn thing seems nearly impossible to get a grip on with these old bones.",
                     "You know this all reminds me of a funny story.~~ Once I was out on a little rowboat with a few pals from work.~~ I used to work delivery service for a local bakery, driving the trucks wherever they needed the bread to go and all, anyway we were out on the water and we were all probably two or three beers in when Dave, he was a pretty big fellow you see, a real mountain of a man, well he realized he needed to piss something fierce.~~ We were all men and told him to just aim off the back side of the boat but the instant he stood up we knew it was all over.~~ His ass stayed in the same spot as he just pushed the back of the boat down into the water and carried the rest of us with it!~~ Lucky it was warm where we ended up, all thanks to him!~~ We had to drag our supplies to shore in handfuls at a time.~~ It was a real mess, but it built character.~~ Well eventually after about an hour or so of frantic salvage we realized we had to get the boat out.~~ So we grabbed some rope and tied it to the back of Dave’s car, figured it was his fault it sank so his car would have to get it.~~ Well, turns out the mud down there was thick because no sooner had Dave started pulling than the lake pulled back and he ended up with his truck stuck in the water too.~~ Not too deep but just enough to keep the wheels stuck.~~ Well, now we’re in a right mess because we know that we can’t tow out Dave and the boat, and we’re all out of rope for the boat.~~ So we left Dave there for and drove off to find someone who could help.~~ Well we’re a little drunk and the cops turned up and next thing we know we’re both in the drunk tank trying to explain why we need to get out and find a tow guy at this hour.~~ By this point the sun’s nearly down and by the time they finally listen to us and we get back Dave’s asleep in the back of his pickup, covered in tackle and empty beer cans.~~ He figured we were gonna be a while so he finished the pack and started fishing again.~~ Well we figured it’d be mighty rude to wake him at this point so we left him on the back of his truck.~~ Problem is that he weighted that sucker down so much it was nearly underwater.~~ So we gave it a good yank with the tow truck and honked his truck when we couldn’t budge and I swear to God the man flew up across that lake rod in hand.~~ Didn’t take long to tow everything back up and we all had a good laugh about it after.~~ Dave never went fishing again without taking an hour to piss himself dry and we gave him all kinds of hell until the day he died.~~ I wonder if he’s still blushing about it up there when I tell that story.",
                     "You know, I think if I could do it all again, I’d just move to Florida and marry the sea.~~ I think I’d have been a lot happier if I were surrounded by other fishermen like me, it’d be less lonely you know?~~ I’m glad you’re here, it’s nice to have someone to talk to after all this time.",
                     "I love fishing in the rain.~~ There’s something about that cool water pouring down on you from the heavens that just brings you closer to the fish you know.~~ We’re sorta linked in the rain, both covered in water and whatnot.~~ Fishing in the snow is miserable though.~~ You’re cold, the fish are cold, neither of you can move because you’re nearly made of ice.~~ Of course ice fishing is a thing I suppose, I never did try it.~~ It always seemed too cold for me, especially now that I’ve got these old bones.~~ But at least they always tell me when it’s going to rain.",
                     "You know, I don’t really get all this technology stuff.~~ Cell phones and computers and whatnot, it’s all alien to me.~~ Guess I’m too old to get it.~~ Old dog, new tricks, and all that jazz.~~ I'm much more of an outdoors kinda guy.~~ I don’t need anything fancy to make me happy.~~ Just the sky, the sea, the fish, and me!~~ I used to say that kinda thing a lot.~~ It rhymes and just rolls off the tongue nicely.~~ Used to drive my wife up the wall but my kids loved it.~~ It always made them laugh when they were little, though as they got older I think they got tired of it too!~~ I know I was a bit tired of hearing my old man say it when I was a kid, but the older I got the more like him I ended up being.~~ So at the end of the day I suppose he passed that phrase on to me.~~ Like a weird sort of inheritance.~~ That and the fishing gear he left me.~~ I’m my father’s son through and through.~~ He raised me off the sea and now here I am practically married to it!~~ Don’t tell my wife I said that.",
                     "This might surprise you but I actually don’t like seafood all that much.~~ There’s only so many ways to salt and cook a fish you know?~~ Well, at least that I know.~~ My wife used to make some wonderful dishes using all kinds of ingredients!~~ Really helped to make each meal a different experience.~~ But I will never ever leave my bologna sandwiches behind!~~ Those things are absolutely perfect.~~ Two pieces of bologna, three slices of yellow american cheese, and white bread!~~ Smushed together and served up with some potato chips, which sometimes I put on the sandwich before I smush them up.~~ It’s much better with them on it and I love having that little extra crunch to it!~~ On top of that if anything falls out of the sandwich or you’ve got supplies left over you can put them on the hook and use that instead of bait!~~ I swear I’ve caught some of the biggest fish I’ve ever seen using some spare bologna.~~ You can take that to the bank!",
                     "Have I ever told you about my greatest catch?~~ Well, when I was a young lad, maybe around your age or so, I took a sweet young lady by the name of Anne out on a rowboat one afternoon.~~ I told her to prepare for a picnic but not to bring anything too big to eat, as I’d be the one to catch us some fresh fish right there on the boat!~~ Well, she obliged me but all the while was jabbing at me about how funny it might be if we didn’t get one single bite the whole time we were out there!~~ Well, we rowed out with the sun high overhead beating down on us and nothing but some light snacks and sodas between our legs.~~ I cast my rod into the water and no more than two minutes had past before I started feeling the strongest tug I ever had!~~ Damn thing nearly tipped the boat over and drug us a good ten feet away from the anchor!~~ Well, I pulled and pulled with all my might and poor Anne was screaming and yelling and trying to not get her nice gown wet, she’d worn a pretty little floral dress her auntie had made for her graduation.~~ Anyway, eventually I got her to grab onto my waist and hold me while I really put my back into reeling this monster up!~~ It fought good and hard the whole way but eventually I’d caught a beast of a salmon nearly four feet long and fat as a pig!~~ Well, it was far too big for the boat so I rowed us back to shore and flayed it there for us to cook up on the grill.~~ While she was preparing something to put on it that’s when I caught her.~~ Pulled the ring right out of my tackle box and got down on my knee.~~ She was hooked that second and I knew I had her for good.~~ Been married ever since then and not a day has gone by that hasn’t been just perfect!~~ Well, except when I spend all hours of the day out here instead of back home, but she understands it and doesn’t fuss about it too much.",
                     "I think spring is by far the best season for fishing, sure the summer’s not half bad but in the spring you can snag ‘em as their heading up to mate in the rivers.~~ It puts me on par with the bears I suppose, circle of life kinda thing.~~ I always try to release those guys though, if I didn't, there wouldn’t be any fish willing to grab my hook after a few years!",
                     "I’ve always thought about buying my own fishing boat.~~ I’ve never really had the money or time for one but I like the idea.~~ Just me and a bunch of other guys braving the high seas and fishing our days away!~~ Of course it’s not that simple, doubt they’d use rods much more nets and whatnot.~~ But it would certainly be a hell of an experience.~~ Would you like to pitch in for one sometime?~~ Ah, what am I saying.~~ I’m far too old for that kinda stuff.~~ You on the other hand… Well, I bet you could do it!",
                     "You ever build a fishing rod?~~ I’ve built a couple in my time, damn things are hard to make!~~ You gotta respect whoever figured these damn contraptions out in the first place, that’s some real human ingenuity!~~ I remember when I started with just some string and a stick I found in the woods, it wasn’t pretty and it barely worked but it felt right.~~ I started putting together proper rods when I was around your age, never built my own parts but would mix and match using spares.~~ I never did build anything that worked better than a standard rod though, suppose I oughta leave that kinda stuff to the professionals!~~ Of course I do consider myself a professional fisherman and I haven’t missed a day’s work since I started, save a few special occasions.~~ Best part of the job is that I don’t have to ask for time off and I can always work extra hours!",
                     "You know, kids these days don’t get enough time like this.~~ Time to just sit and enjoy nature.~~ That’s the best part of fishing, if you don’t catch anything you’ve still had all sorts of time to relax and take in the world around you.~~ It’s sorta peaceful, lets you collect your thoughts, like a meditation thing.~~ You can just let yourself become a part of the world around you, in tune with the environment.~~ Once you let yourself go like that you can really start to understand the fish.~~ You almost become one of them.~~ You don’t really, but could you imagine that?~~ A fish with a fishing pole!~~ Just snatching up other fish.~~ Wonder what he’d do with ‘em?~~ Would he eat them?~~ I suppose something like a shark or a barracuda would.~~ A trout on the other hand, I dunno, I suppose he’d practice catch and release.~~ It’s almost like dating.~~ There are plenty of fish in the sea after all!",
                     "You know I worked on a fishing boat for a few years.~~ It’s a fantastic experience, just you and the rest of the crew out at sea.~~ You build some real life long friends that way, though it is hard for a family man.~~ Brings in good money though and it’s certainly a fun time for those aboard.~~ It’s dangerous though, we nearly lost a couple of guys more than once.~~ You’ve gotta pay attention and keep your wits about you in that environment, especially if a storm kicks up.~~ I stayed on as long as my wife would let me, but eventually she and the kids made me come home.~~ I do miss it sometimes but at the end of the day I don’t regret coming home for a second.~~ I would’ve missed the most important moments in my children’s lives out on the sea like that.~~ Assuming I didn’t get swept away.~~ I stayed in touch with those guys as best I could but I’m the only one left now.~~ Some things aren’t meant to last, I suppose, all good things and such.~~ I do miss it though.~~ It’s not the same sitting here like this, even with that salty sea spray wafting through my hair.~~ There’s something about the way the waves rock you as though the sea is fighting to keep her fish within.~~ Fishing like this though, she almost hands them off.~~ Welcoming me to take them.~~ I wonder why that is, what makes her so much calmer when you fish just off the shore?",
                     "I’ve always wondered what whaling would be like?~~ It’s crazy when you think about it, trying to hunt something that’s so much bigger than even the boat you’re on.~~ It’s just not something man was meant to do, I don’t think.~~ Smaller fish like these are easy pickings, meant to be caught and eaten by people like you and me.~~ Those beasts, they’re not for us to hunt.~~ Yet we find a way.~~ I suppose that’s human ingenuity for you.~~ If there’s a task we set our sights on we’ll find a way eventually!~~ Still, doesn’t mean we always should.~~ Some things are just meant to be the way they are.~~ Can’t change too much or you risk changing everything and then what you’ve got ain’t even close to what you started with.~~ But that doesn’t mean we shouldn’t try, I suppose.~~ If we stopped everytime we started we would never have gotten where we are today.~~ But that’s just what this old man thinks, you youngins have your own thoughts on the world.~~ Pretty different from my own too.~~ I guess it’s your world now, to do with as you please.~~ Though I admit I was never much involved in it myself.~~ People are hard, you know?~~ Hard to reason with, no patterns, we do the darndest things sometimes don’t we.~~ Fish on the other hand, they’re creatures of habit.~~ Following their instincts and whatnot.~~ Why, if I were a fish I bet I’d live much as I do now!~~ Though I suppose I wouldn’t be a fisherman anymore!~~ It’d be weird if I was, could you imagine a fishing fish?~~ Sounds like something you’d see on TV.~~ Though I don’t care much for TV.~~ It’s much better to sit and watch the clouds roll by than to sit glued to the telly, though I do bring my radio out with me from time to time.~~ It can be nice if you’re alone to have some connection, though most of the time I prefer the sounds of the wind and the waves over anything else.",
                     "You play any video games?~~ My grandkids tried to get me to join them on some kinda racing game one Christmas, I could hardly understand it.~~ They mopped the floor with me to say the least.~~ But later that night, once they were in bed my daughter showed me the sweetest thing.~~ They’d bought some fishing video games and the kids loved it because they could be just like me!~~ Could you imagine that?~~ Some little kids wanting to be just like me?~~ It nearly broke my heart.~~ I tried my hand at it too and I think I did alright, it’s not the same as really fishing but it was pretty fun.~~ I hope they come out here one day to join me, so they can see what it’s really like.~~ Maybe you’ll get to meet them.~~ Wouldn’t that be swell?",
                     "Once I got swept out to sea.~~ There was a massive storm that didn’t seem too bad until it was too late.~~ It took my boat up in it and carried me far out into the open waters.~~ I could barely see the shoreline once it cleared and I sure am lucky it didn’t toss me or my fishing pole overboard.~~ It took me nearly a week or so to row back to safety.~~ I only survived by fishing and eating everything I could catch.~~ To be honest I don’t think I would have made it if it weren’t for my lucky pole.~~ Once she goes in the water she’s sure to hook something within a few minutes.~~ Hasn’t let me down once.~~ I made it back to shore with my pride intact, though I was mighty thirsty.~~ My wife made me stay home for a long time after that and insisted someone came with me once I finally argued my way into being let back out onto the sea.~~ I don’t know what I would have done if she hadn’t but I must admit it was scary as all hell.~~ I think that’s the worst way to die, alone like that, slowly withering away.~~ I’m planning on dying right here one day.~~ I hope they find me asleep here, fishing pole still in hand.~~ Sorry, I get a bit morbid when I think about that stuff.~~ Who knows, I’ve made it this far.~~ Maybe I’ll live forever!",
                     "You know people always say that fishermen exaggerate their stories.~~ I don’t think that’s true.~~ I’ll tell you I haven’t told a tall tale once in my life.~~ Why if I ever have it’s only because my memory is somewhat shot these days.~~ I’m not really lying, I just don’t know what the truth is anymore!~~ Drives people up the wall whenever I’m talking to them, they swear I’ve told them the same stories before and that I’ve changed them.~~ I’ll have you know that to be frank I don’t know what I have and haven’t said to you and don’t really mind it all that much.~~ So long as someone is willing to sit and listen I’m willing to tell my stories to them.~~ You’ve been a good listener.~~ I really like fishing with you.",
                     "You ever tried fly fishing?~~ It’s a damn nightmare!~~ I don’t understand any part of that process!~~ Personally I much prefer the good old fashioned rod and reel action I’ve got going on right here.~~ Every single time I’ve tried fly fishing I’ve snaged my hat, my jacket, the bushes, the boat, my buddies, you name it I’ve caught it fly fishing, so long as you don’t name fish!~~ Besides, it’s a little too fast for my tastes.~~ Fishing is done best when you’re doing it slow and steady.~~ It gives you that kinda thinking time you don’t get too many other places.~~ It’s peaceful, serene even.~~ I could never fish standing up these days.~~ My old bones could never last that long!~~ Why I’m surprised I can still move my hands as well as I can.~~ Still, have a damn hard time opening up cans of bait and tying hooks on but I’ll be damned if there’s a day I can’t.~~ I’ll probably be dust one day with a pair of good hands that are still catching fish out here!~~ Maybe they’ll tell ghost stories about me to young sailors?~~ I’ve never been a fan of those sorts of things, it’s the sort of stuff that’s just used to spook the young guys on deck and get the older guys laughing.~~ Though there are true stories of course, you’ve gotta learn which those are.~~ That’s the key to surviving at sea.~~ Lest ye wanna meet a watery grave.~~ Least that’s what they used to say!~~ These days I suppose most of them are true, better safe than sorry!~~ I’ve still got fish to catch, don’t have time for the ghosts of drowned maidens to drag me down!~~ I hope one day you’ll have worthy tales yourself, I hope mine are worthy too.",
                     "What’s the deal with all this social media stuff these days?~~ I don’t really get it.~~ Of course I made a Facebook page and whatnot to keep in touch with everybody I know.~~ I hardly use it though, it’s a bunch of bologna anyway.~~ I don’t need any of your “friend points” or whatever the hell they’re called to make me happy.~~ All I need are the fish.~~ They understand me, much better than anyone else does.~~ Well, I think you understand me, at least a little bit.~~ You listen to me.~~ You spend time with me.~~ You care about me.~~ Don’t you?~~ I care about you.~~ You’re my only real friend.",
                     "Some fellas drink while they fish, I used to be one of them, but it’s no fun really.~~ You always drink and fish on a summer afternoon.~~ So you’re drunk, hot, and sweaty as a pig.~~ Not to mention how rowdy most guys get once they’ve had a few.~~ How do you expect to catch any fish if you’re shouting at them?~~ I once left a fishing trip as soon as I saw that one of the guys had brought a cooler and a boombox with him.~~ I don’t have time to put up with that kinda shit!~~ It’s so much nicer to just sit and watch the waves come in.~~ Don’t need music, don’t need booze, don’t even really need a good conversation.~~ Just need that sorta peaceful nature to lull you in.~~ It keeps you calm.~~ You’re just resting.~~ And then… BAM!~~ That’s when you get a fish on the line!~~ And your heart gets pumping and you’re in it for the thrill!~~ You’re fighting that little bastard and then suddenly it’s over, as soon as it started.~~ Either he’s gotten away and snapped your line, or you’re looking him right in the eye and telling’ him you beat ‘im.~~ It’s always a pain in the ass when he takes a good lure though.~~ I’ve lost quite a few to some clever ones here and there.~~ That’s why I don’t bother with the expensive crap.~~ You’re going to lose it somehow and you could do just as good with a shoelace and some leftovers as with some $40 lure and $60 bait.~~ It’s a waste of money it is.~~ Fishing is simple, it’s up to people like us to keep it that way."
                     ];
